### PR TITLE
Add hackathon winners to the hackathon page

### PR DESCRIPTION
**Pull request by eulphean**
Changes for #83 

Added a new WinnerCard and WinnersContainer with team names, descriptions, and bounties for the winning  projects

### CODE REVIEW

**Comment by eulphean** [comment]
@trbutler4 
Sure. To reiterate. 
1. Create a new page with Hackathon Winners
2. Add a link to this page from the Hackathon page
3. Add a new (image) button on the top left, which links to the Hackathon Winners
image

**Comment by trbutler4** [comment]
> @trbutler4 Sure. To reiterate.
> 
> 1. Create a new page with Hackathon Winners
> 2. Add a link to this page from the Hackathon page
> 3. Add a new (image) button on the top left, which links to the Hackathon Winners
> 
> image

yes, and I also think it would look a bit cleaner if there was seperated between each card, with the grid background showing behind them to match the styling of the other pages. Maybe drop the pink color, and just have each card be red. I dont really like the pink (lol)

**Comment by trbutler4** [comment]
thank you!

**Comment by trbutler4** [comment]
a red border around the hackathon project images, on top of a navy card would look pretty clean imo but open to other suggestions

**Comment by trbutler4** [comment]
any thoughts on styling? @adrian-petrykiw

**Comment by eulphean** [comment]
I tried the navy color background for the cards and black/red backgrounds - it looked sad af. 
but I can try it with the new grid background. 
maybe it'll pop up.

**Comment by eulphean** [comment]
@trbutler4 
All changes implemented. Good idea on using the Blue for the winner cards. I think with the grid, it looks much better. Check out these images. 

Card2
Card

**Comment by eulphean** [comment]
@ping 
@adrian-petrykiw @trbutler4 
Can you please review this and let me know what changes you guys need?

**Review by trbutler4 — APPROVED** [review]
looking good. thanks for updating!

**Pull request merged**
